const products = [
  {
    id: "1",
    category: "Bedsheets",
    name: "Sunshine Blossom Bedsheet",
    salePrice: 1200,
    minPrice: 1140,
    paidPrice: 0,
    image: "https://instagram.com/p/Cz3A4x9ocxi/media/?size=l",
  },
  {
    id: "2",
    category: "Towels",
    name: "Kid’s Towel Collection",
    salePrice: 450,
    minPrice: 420,
    paidPrice: 0,
    image: "https://instagram.com/p/Cx1P0DFJk8e/media/?size=l",
  },
  {
    id: "3",
    category: "Quilts",
    name: "Handblock Cotton Quilt",
    salePrice: 2500,
    minPrice: 2375,
    paidPrice: 0,
    image: "https://instagram.com/p/Cw0q9_xL2uV/media/?size=l",
  },
  {
    id: "4",
    category: "Tablecloths",
    name: "6-Seater Cotton Tablecloth",
    salePrice: 850,
    minPrice: 800,
    paidPrice: 0,
    image: "",
  },
  {
    id: "5",
    category: "Bathrobes",
    name: "Waffle Cotton Bathrobe",
    salePrice: 1800,
    minPrice: 1700,
    paidPrice: 0,
    image: "https://instagram.com/p/CxvZC2apUWo/media/?size=l",
  },
  {
    id: "6",
    category: "Cushions",
    name: "Handblock Cushion Covers",
    salePrice: 600,
    minPrice: 570,
    paidPrice: 0,
    image: "https://instagram.com/p/Cy8NAkQvA7J/media/?size=l",
  },
];

export default products;
